services:
  cego-dev:
    container_name: cego-dev
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app/backend:cached
      - ./tests:/app/tests:cached
      - ./benchmarks:/app/benchmarks:cached
      - ./data:/app/data:cached
      - model-cache:/app/models
    environment:
      - ENV=development
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - WATCHDOG_ENABLE=true
      - MAX_WORKERS=2
      - MEMORY_LIMIT_MB=512
      - CACHE_SIZE_MB=128
    ports:
      - "8001:8000"  # CEGO Dev API on 8001
      - "9091:9090"  # CEGO Dev Metrics on 9091
    command: python -m uvicorn backend.api.main:app --reload --host 0.0.0.0 --port 8000

  cego-prod:
    container_name: cego-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - ENV=production
      - MAX_WORKERS=4
      - MEMORY_LIMIT_MB=1024
      - CACHE_SIZE_MB=256
    ports:
      - "8002:8000"  # CEGO Prod API on 8002
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2'
        reservations:
          memory: 512M
          cpus: '1'

  cego-test:
    container_name: cego-test
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./tests:/app/tests
      - ./backend:/app/backend
    environment:
      - ENV=test
      - PYTHONPATH=/app
    command: pytest -v --cov=backend --cov-report=term-missing

volumes:
  model-cache: